"""
=============================================================
  Ragas RAG Evaluation — Chunk Attribution & Utilization
  Works with: Azure OpenAI (primary) or OpenAI (fallback)
=============================================================
"""

import os
from dotenv import load_dotenv
from datasets import Dataset
import pandas as pd

from ragas import evaluate
from ragas.metrics import (
    faithfulness,          # → Chunk Attribution  (was answer grounded in chunks?)
    context_precision,     # → Chunk Utilization  (were retrieved chunks useful?)
    context_recall,        # → did we retrieve all needed chunks?
    answer_relevancy,      # → is the answer relevant to the question?
)

from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings

load_dotenv()

# ─────────────────────────────────────────────────────────────
# 1. Configure Azure OpenAI models
# ─────────────────────────────────────────────────────────────
def get_azure_models():
    llm = AzureChatOpenAI(
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-01"),
        azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o"),
        temperature=0,
    )

    embeddings = AzureOpenAIEmbeddings(
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-01"),
        azure_deployment=os.getenv("AZURE_OPENAI_EMBED_DEPLOYMENT", "text-embedding-ada-002"),
    )

    return llm, embeddings


# ─────────────────────────────────────────────────────────────
# 2. Sample RAG data  (replace with your real pipeline output)
#    Each row = one user query through your RAG system
# ─────────────────────────────────────────────────────────────
RAG_SAMPLES = [
    {
        # Query sent by user
        "question": "What is Azure OpenAI Service and what models does it support?",

        # Chunks retrieved from your vector store / Azure AI Search
        "contexts": [
            "Azure OpenAI Service provides REST API access to OpenAI's powerful language models including GPT-4, GPT-3.5-Turbo, and Embeddings model series.",
            "The service runs on Azure infrastructure and supports private networking through VNet integration and private endpoints.",
            "Azure OpenAI supports fine-tuning on GPT-3.5-Turbo and Babbage models to customize them for specific use cases.",
            "Microsoft Excel was first released in 1985 for the Apple Macintosh.",  # ← intentional noise chunk
        ],

        # Answer generated by your LLM
        "answer": "Azure OpenAI Service is a cloud offering by Microsoft that provides REST API access to OpenAI models such as GPT-4 and GPT-3.5-Turbo. It supports private networking via VNet and allows fine-tuning on select models.",

        # Ground truth — what the correct answer should be
        "ground_truth": "Azure OpenAI Service provides access to OpenAI models like GPT-4 and GPT-3.5-Turbo via REST APIs on Azure infrastructure, with support for private networking and fine-tuning.",
    },
    {
        "question": "How does RAG help reduce hallucination in LLMs?",
        "contexts": [
            "Retrieval-Augmented Generation (RAG) grounds LLM responses in external documents retrieved at query time, reducing hallucination.",
            "By conditioning the model on retrieved context, RAG ensures answers are factually tied to source material rather than model memory.",
            "RAG pipelines typically use a vector database like Azure AI Search to retrieve semantically similar chunks.",
            "Python was created by Guido van Rossum and first released in 1991.",  # ← noise chunk
        ],
        "answer": "RAG reduces hallucination by grounding LLM responses in retrieved documents. Instead of relying on model memory, the LLM generates answers based on retrieved chunks from a vector store like Azure AI Search.",
        "ground_truth": "RAG reduces hallucination by conditioning the LLM on external documents retrieved at query time, ensuring answers are tied to real source material.",
    },
    {
        "question": "What is EF Core and how does it work with SQL Server?",
        "contexts": [
            "Entity Framework Core (EF Core) is a lightweight, extensible, open source ORM for .NET.",
            "EF Core supports SQL Server via the Microsoft.EntityFrameworkCore.SqlServer package.",
            "EF Core uses DbContext to manage entity objects during runtime, which includes querying and saving data.",
            "EF Core migrations allow developers to incrementally update the database schema to keep it in sync with the application model.",
        ],
        "answer": "EF Core is a .NET ORM that enables developers to work with SQL Server using .NET objects. It uses DbContext for managing queries and saving data, and supports migrations to keep the database schema in sync with the application model.",
        "ground_truth": "EF Core is an open source .NET ORM. It supports SQL Server via a dedicated package, uses DbContext for data access, and provides migrations for schema management.",
    },
]


# ─────────────────────────────────────────────────────────────
# 3. Build Hugging Face Dataset (required by Ragas)
# ─────────────────────────────────────────────────────────────
def build_dataset(samples):
    return Dataset.from_dict({
        "question":     [s["question"]     for s in samples],
        "contexts":     [s["contexts"]     for s in samples],
        "answer":       [s["answer"]       for s in samples],
        "ground_truth": [s["ground_truth"] for s in samples],
    })


# ─────────────────────────────────────────────────────────────
# 4. Run Evaluation
# ─────────────────────────────────────────────────────────────
def run_evaluation():
    print("\n" + "="*60)
    print("  Ragas RAG Evaluation — Chunk Attribution & Utilization")
    print("="*60)

    print("\n[1/3] Connecting to Azure OpenAI...")
    llm, embeddings = get_azure_models()
    print("      ✓ Azure OpenAI connected")

    print("\n[2/3] Building dataset...")
    dataset = build_dataset(RAG_SAMPLES)
    print(f"      ✓ {len(RAG_SAMPLES)} samples loaded")

    print("\n[3/3] Running Ragas evaluation (this may take 1-2 mins)...")
    print("      Metrics: faithfulness | context_precision | context_recall | answer_relevancy\n")

    results = evaluate(
        dataset=dataset,
        metrics=[
            faithfulness,       # Chunk Attribution
            context_precision,  # Chunk Utilization
            context_recall,
            answer_relevancy,
        ],
        llm=llm,
        embeddings=embeddings,
        raise_exceptions=False,
    )

    # ─── Print Results ───────────────────────────────────────
    print("\n" + "="*60)
    print("  RESULTS")
    print("="*60)

    print("\n📊 Aggregate Scores:")
    print(f"   Faithfulness    (Chunk Attribution)  : {results['faithfulness']:.4f}  — was answer grounded in retrieved chunks?")
    print(f"   Context Precision (Chunk Utilization): {results['context_precision']:.4f}  — were retrieved chunks actually useful?")
    print(f"   Context Recall                       : {results['context_recall']:.4f}  — were all needed chunks retrieved?")
    print(f"   Answer Relevancy                     : {results['answer_relevancy']:.4f}  — was the answer relevant to the question?")

    # Per-sample breakdown
    df = results.to_pandas()
    print("\n📋 Per-Sample Breakdown:")
    pd.set_option("display.max_colwidth", 60)
    pd.set_option("display.float_format", "{:.4f}".format)
    print(df[["question", "faithfulness", "context_precision", "context_recall", "answer_relevancy"]].to_string(index=True))

    # Save to CSV
    output_path = "ragas_results.csv"
    df.to_csv(output_path, index=False)
    print(f"\n✅ Full results saved to: {output_path}")

    # Score interpretation
    print("\n📖 Score Guide:")
    print("   0.0 - 0.4  → Poor   | chunks not being used / answer hallucinated")
    print("   0.4 - 0.7  → Fair   | partial grounding / some irrelevant chunks")
    print("   0.7 - 1.0  → Good   | answer well grounded in retrieved context")

    return results


# ─────────────────────────────────────────────────────────────
# 5. Entry Point
# ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    run_evaluation()
